### ISSUE TITLE
Unmatched queries?

### ISSUE THREAD

**Issue by niksy** [weblinc/nonresponsive#2]
Is this reliable in matching larger set of media queries?

I’ve tried it on uncompressed large file and it didn’t match it fully, but Respond.js did match everything.
It seems to be related to regular expression used to parse media blocks.
Should the style be compressed in start or does your expression caters to new lines, breaks, tabs and such?

I would like to use Nonresponsive with Media Match to have the whole stack on your scripts (Media Match is excellent!), but this—and styles parsing and fetching, but I can create my own fetcher—prevents me to use this in production environment.

**Comment by knightdr** [comment]
@niksy 

I'd have to see your css to see what might be tripping up the regex. It shouldn't matter whether the css is compressed or not. Thanks for Media Match's positive feedback. Again, I'd like to see where the regex is failing so if you could provide a sample, I may be able to help.

**Comment by frenic** [comment]
Hi, I'm having the same issue. I really think this has great potential. But I found out that uncompressed CSS doesn't match anything. But if you remove the last line break, it all matches.

``` css
/* Doesn't match */
@media only screen and (min-width: 30em) {
  .main-footer__top .nav {
    width: 50%;
    padding-right: 24px;
    padding-right: 1.5rem;
  }
}

/* Does match */
@media only screen and (min-width: 30em) {
  .main-footer__top .nav {
    width: 50%;
    padding-right: 24px;
    padding-right: 1.5rem;
  }}
```

One other thing I noticed is that the url(...) values in the stylesheets breaks. RespondJS does a pretty simple update of these values. Is this something you would consider also?
